name: Generate SAM CLI JSON schema

on:
  pull_request:
    branches:
      - develop
      - "feat/*"
      - "SANDBOX-*"
  
jobs:
  generateSchema:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout latest AWS SAM CLI commit
        with:
          repository: 'aws/aws-sam-cli'
          ref: 'feat-json-schema'
          path: 'aws-sam-cli-feat-json-schema'
      - uses: actions/setup-python@v4
        name: Install Python 3.9
        with:
          python-version: 3.9
      - run: |
          ls
          python schema/make_schema.py
          cat schema/samcli.json
          name: Generate the schema
          shell: bash
