name: Generate SAM CLI JSON schema

on:
  schedule:
    - cron: 30 15 * * 1-5  # 8:30am PST Monday-Friday
  pull_request:
    branches:
      - develop
      - "feat/*"
      - "SANDBOX-*"
  
jobs:
  generateSchema:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout latest AWS SAM CLI commit
        with:
          repository: 'aws/aws-sam-cli'
          ref: 'develop'
          path: 'aws-sam-cli-develop'
      - uses: actions/setup-python@v4
        name: Install Python 3.9
        with:
          python-version: 3.9
      - run: |
          make -C aws-sam-cli-develop init
          cd aws-sam-cli-develop
          diff <( cat schema/samcli.json ) <( python schema/make_schema.py; cat schema/samcli.json ) && exit 0 # exit if schema is unchanged
          echo "The generated schema differs from that in the PR. Please run 'make schema'."
          exit 1
          name: Generate the schema
          shell: bash
